### ISSUE TITLE
may hit cloudflare subdomain limit

### ISSUE THREAD

**Issue by tasi788** [lockerpm/maily#2]
https://github.com/lockerpm/maily/blob/9f1aa3bae22ec7133a7cfa334eab70c5c9db4b5f/src/maily/domain_identity.py#L41-L50

In this code, it seems there is no exception handling, and there could also be potential issues. According to Cloudflare community, there are only 1000 subdomain records for the free plan and 3500 for the paid plan, whereas the Enterprise plan differs. But from what can be seen currently, maily.org seems only to be using the free or pro plan. Do we have any future plans regarding this?

edit:
ref: https://community.cloudflare.com/t/limit-on-dns-records-per-domain/415781

**Comment by dangzed** [comment]
Hi @tasi788 , thank you for the reported issue, we are aware of this problem and still finding the optimal solution.

**Comment by tasi788** [comment]
It seems that the commit cde1768fb50690ada9564c45dbee5fb8248625cd has already fixed the problem, so I am closing the issue.
