### ISSUE TITLE
Attachment limit to small

### ISSUE THREAD

**Issue by tasi788** [lockerpm/maily#3]
https://github.com/lockerpm/maily/blob/9f1aa3bae22ec7133a7cfa334eab70c5c9db4b5f/src/maily/message.py#L218

According to AWS SES page says. _Amazon Simple Email Service (Amazon SES) customers can now request a limit increase to send and receive emails with a message size of up to 40MB._

Maybe attachment size limit can increase up to 25MB ?

https://aws.amazon.com/tw/about-aws/whats-new/2021/09/amazon-ses-emails-message-40mb/

**Comment by bestpika** [comment]
The attachment size limit for Gmail is also 25 MB, so it would be reasonable to increase the email capacity to slightly more than 25 MB.

**Comment by everping** [comment]
Hi @tasi788,

We are considering this matter and will get back to you soon.

**Comment by dangzed** [comment]
Hi @tasi788, 

We have increased the email capacity to 25MB.
